version: "3.8"

services:
  milvus:
    image: milvusdb/milvus:v2.5.0
    container_name: milvus
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./milvus_data:/var/lib/milvus
